language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

branches:
    only:
        - master

matrix:
    include:
        - php: 5.4
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 5.5
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 5.6
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 7.0
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

before_script:
    - composer update --prefer-source --dev

script:
    - bin/phpspec run -fpretty
